runtime: python37
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /favicon\.png
  static_files: favicon.png
  upload: favicon\.png
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
